### ISSUE TITLE
No country name tooltips associated with country flags

### ISSUE THREAD

**Issue by CaryV** [binhex/arch-delugevpn#44]
Seems to be an issue / enhancement handled by Deluge (per ticket# 259) about ten years ago, yet...
The binhex (docker) version of delugevpn that I downloaded and installed in unRAID does not seem have such a feature enabled in its webGUI.  What does it take to enable such a feature?  Is there a plug-in readily available?  I can't find anything further on the issue, except that Deluge 'fixed' it years ago, but that patch applied to the GTK UI, not the WebGUI.  Thanks.
BTW The DelugeVPN docker worked great the first time out and provided for an excellent configuration with VPN and Privoxy included.  Wish all apps were to easy to install and configure.

**Comment by CaryV** [comment]
That's nice - Case Closed, but NO RESOLUTION...
Where are the tooltips that this pertains to?
It's only been 2-1/2 years in the making - for an issue that was resolved in Deluge
over 12 years ago!

**Comment by binhex** [comment]
im on my own here with at last count 67 repositories to support, things get missed or left out that is how it is.

move on in time and we are now at deluge v2 which is very different to deluge v1, so this issue may not be relevant anymore, thus the close, if its still a problem then please confirm and re-raise.

**Comment by binhex** [comment]
one last thing to add to this, i would confirm on the deluge forums that country name tooltips is available via the web ui, it might be that it is simply is not possible and only is availble via full fat gtk ui.
